import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { LogOut, User, ShieldAlert, AlertTriangle } from 'lucide-react';
import logoUrl from '../assets/logo.svg';
import './Dashboard.css';

const Dashboard = () => {
  const [logs, setLogs] = useState([]);
  const [aiAlerts, setAiAlerts] = useState([]);
  const [accounts, setAccounts] = useState([]);
  
  const navigate = useNavigate();
  const role = localStorage.getItem('role');
  const username = localStorage.getItem('username');
  const token = localStorage.getItem('token');

  useEffect(() => {
    if (!token) {
      navigate('/login');
      return;
    }

    if (role === 'ROLE_SUPER_ADMIN' || role === 'ROLE_ADMIN' || role === 'ROLE_COMPLIANCE_OFFICER') {
      fetch('http://localhost:8080/api/audit/logs', {
        headers: { 'Authorization': `Bearer ${token}` }
      })
      .then(res => res.json())
      .then(data => setLogs(data))
      .catch(err => console.error(err));

      if (role === 'ROLE_SUPER_ADMIN') {
        fetch('http://localhost:8080/api/ai/alerts', {
          headers: { 'Authorization': `Bearer ${token}` }
        })
        .then(res => res.json())
        .then(data => setAiAlerts(data))
        .catch(err => console.error(err));
      }
    }

    if (role === 'ROLE_CUSTOMER' || role === 'ROLE_TELLER' || role === 'ROLE_BRANCH_MANAGER') {
      fetch('http://localhost:8080/api/accounts', {
        headers: { 'Authorization': `Bearer ${token}` }
      })
      .then(res => res.json())
      .then(data => setAccounts(data))
      .catch(err => console.error(err));
    }
  }, [token, role, navigate]);

  const handleLogout = () => {
    localStorage.clear();
    navigate('/login');
  };

  return (
    <div className="dashboard-container">
      <nav className="navbar">
        <div className="nav-brand" style={{display: 'flex', alignItems: 'center', gap: '0.5rem'}}>
          <img src={logoUrl} alt="Bank Of Captcha Logo" width="24" height="24" />
          BANK OF CAPTCHA
        </div>
        <div className="nav-user">
          <User size={20} />
          <span>{username} ({role})</span>
          <button className="logout-btn" onClick={handleLogout}>
            <LogOut size={16} /> Logout
          </button>
        </div>
      </nav>

      <main className="dashboard-main">
        {role === 'ROLE_CUSTOMER' ? (
          <div className="customer-view">
            <h2>Welcome, {username}!</h2>
            {accounts.map(acc => (
              <div key={acc.id} className="balance-card">
                <h3>Account: {acc.accountNumber}</h3>
                <div className="balance-amount">${acc.balance}</div>
              </div>
            ))}
          </div>
        ) : role === 'ROLE_SUPER_ADMIN' ? (
          <div className="admin-view">
            <h2><AlertTriangle size={24} color="#f44336" /> AI Misuse Alerts</h2>
            <p>Alerts generated by the AI Privileged Account Misuse Detection Module.</p>
            <div className="logs-table-container" style={{marginBottom: '2rem'}}>
              <table className="logs-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Flagged User</th>
                    <th>Severity</th>
                    <th>Description</th>
                    <th>Timestamp</th>
                  </tr>
                </thead>
                <tbody>
                  {aiAlerts.map(alert => (
                    <tr key={alert.id} style={{backgroundColor: alert.severity === 'HIGH' ? '#ffebee' : ''}}>
                      <td>{alert.id}</td>
                      <td><strong>{alert.flaggedUsername}</strong></td>
                      <td style={{color: alert.severity === 'HIGH' ? 'red' : 'orange'}}>{alert.severity}</td>
                      <td>{alert.description}</td>
                      <td>{new Date(alert.timestamp).toLocaleString()}</td>
                    </tr>
                  ))}
                  {aiAlerts.length === 0 && (
                    <tr>
                      <td colSpan="5" style={{textAlign: 'center'}}>No AI alerts generated.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            <h2><ShieldAlert size={24} /> Audit Logs</h2>
            <div className="logs-table-container">
              <table className="logs-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Action</th>
                    <th>Timestamp</th>
                  </tr>
                </thead>
                <tbody>
                  {logs.map(log => (
                    <tr key={log.id}>
                      <td>{log.id}</td>
                      <td><span className="log-user">{log.username}</span></td>
                      <td>{log.action}</td>
                      <td>{new Date(log.timestamp).toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ) : (
          <div className="admin-view">
            <h2><User size={24} /> Staff Dashboard</h2>
            <p>Welcome to the staff portal.</p>
            {role === 'ROLE_TELLER' || role === 'ROLE_BRANCH_MANAGER' ? (
              <div className="logs-table-container">
                <h3>Customer Accounts Overview</h3>
                <table className="logs-table">
                  <thead>
                    <tr>
                      <th>Account Number</th>
                      <th>Owner ID</th>
                      <th>Balance</th>
                    </tr>
                  </thead>
                  <tbody>
                    {accounts.map(acc => (
                      <tr key={acc.id}>
                        <td>{acc.accountNumber}</td>
                        <td>{acc.user?.id}</td>
                        <td>${acc.balance}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : null}
            
            {(role === 'ROLE_COMPLIANCE_OFFICER' || role === 'ROLE_ADMIN') && (
              <div className="logs-table-container">
                <h3>System Audit Logs</h3>
                <table className="logs-table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>User</th>
                      <th>Action</th>
                      <th>Timestamp</th>
                    </tr>
                  </thead>
                  <tbody>
                    {logs.map(log => (
                      <tr key={log.id}>
                        <td>{log.id}</td>
                        <td><span className="log-user">{log.username}</span></td>
                        <td>{log.action}</td>
                        <td>{new Date(log.timestamp).toLocaleString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
};

export default Dashboard;
